### ISSUE TITLE
Uncaught FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore[BUG] title

### ISSUE THREAD

**Issue by filmerjarred** [tylim88/FirelordJS#91] opened 2023-02-06 06:36 UTC
Using the latest version with the example code, I'm seeing this:

![image](https://user-images.githubusercontent.com/2033608/216898984-58bad035-5559-496c-8702-6d30ef927cd4.png)

![image](https://user-images.githubusercontent.com/2033608/216899110-5fba6c90-d0e3-4529-aaee-36f2b5b1a497.png)

narrowed it down to this minified code in the firebase module

![image](https://user-images.githubusercontent.com/2033608/216899276-a3ad28f0-baac-4c37-bb10-603ba6bfad7f.png)

which I'm pretty sure this this

![image](https://user-images.githubusercontent.com/2033608/216899546-814c9487-ae9a-4b7c-a97c-61951cd2b14f.png)

I think something weird is going on with the classes, and the firestore instance that firelord lib ends up with isn't registering as the same class that the firestore lib has.

Have this library been used on the frontend before?

**Comment by tylim88** [comment] 2023-02-06 12:32
may I know which step went wrong?

is it `setDoc`?

I tested it on [codesandbox](https://codesandbox.io/s/empty-leaf-z9brsl?file=/src/App.tsx) and I cannot reproduce what you (replace `your-projedct-id` and set your permission)

**Comment by tylim88** [comment] 2023-02-06 12:37
also may I know firelordJS and firebase version you are using?

**Comment by ArStah** [comment] 2023-02-06 16:37
Got the same error, seems that the problem is in `firebase@9.17.1`, works fine with `firebase@9.16.0`

**Comment by tylim88** [comment] 2023-02-06 16:59
I am not able to reproduce the error with `firebase@9.17.1` (the codesandbox use 9.17.1), I need a repo that can reproduce the error

**Comment by filmerjarred** [comment] 2023-02-06 22:41
Thanks for the reply, here's a demo repo https://github.com/filmerjarred/firelord-react-issue/blob/main/src/App.tsx

Also note, I fixed a different error "could not find service firestore" by adding the second line import "firebase/firestore"

I think the issue is related to the bundling / magic that goes on with imports, and why it works in codepen is because they do bundling in a different way. If you pull that repo, npm install and then run start it should reproduce the error

**Comment by tylim88** [comment] 2023-02-06 22:55
is all of your error happen when you use react-script v5?

**Comment by tylim88** [comment] 2023-02-06 22:59
please use react script v4.0.3

my guess is this is related to webpack v5

as far as I know react script v5 use webpack v5, and webpack v5 does not fill nodejs module for you

some(many) client side library use nodejs module, so webpack v5 break a lot of thing

I recommend you use react script v4.0.3 or switch to react vite to make your life easier

**Comment by tylim88** [comment] 2023-02-06 23:00
I will close this post in few more hours (I don't want it exceed 24 hours)

Please try react-script v4.0.3 and let me know

**Comment by tylim88** [comment] 2023-02-06 23:20
hmm, interesting, v5.0.1 works with firebase without any issue

something is indeed wrong with firelord

**Comment by tylim88** [comment] 2023-02-07 00:25
currently this is my understanding:

1. this is not about node module, because react-scripts can run firebase fine
2. most likely this is bundling as you said, webpack somehow alter firelordjs firestore instance
3. I triple checked my code and pretty sure I did not alter the firestore instance by any mean, firelordjs simply passing the instance around

I decided not to troubleshoot as I think this is a waste of time(it is very difficult to troubleshoot with react-script 5.0.1)

If you want to use firelordjs in existing project, simply downgrade react-scripts to v4.0.3
If you want to use firelordjs in new project, please use vite react

react-scripts is no longer a good tool, with a lot of frustrations and 0 update in the last 10 months

I will close this issue, if both solutions do not work for you, open new issue

If you want to reach me faster, you can find me in the discord

**Comment by ArStah** [comment] 2023-02-07 09:06
My issue is not related to react-script, since I use vue3, nuxt3 and vite as builder. And firelordjs works fine with `firebase@9.16.0`. I'll do reproduction repo later, don't have time now

**Comment by tylim88** [comment] 2023-02-07 16:04
it seem like what firebase 9.16 does work with react scripts v5.0.1

and we can also see the same error in react vite

so the problem lie in what had changed in firebase 9.17.l

**Comment by tylim88** [comment] 2023-02-07 17:58
After some troubleshooting I finally understand what is happening

first when we try to google `Uncaught FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore[BUG] title`, this is the first thing that come up: https://stackoverflow.com/a/69048162/5338829

![image](https://user-images.githubusercontent.com/5227509/217317266-bf7477ba-1c8a-426a-b5c5-2aa543548453.png)

second when we try to search `Expected first argument to collection()` in the sdk codebase, this is what we got
![image](https://user-images.githubusercontent.com/5227509/217317467-a3dc66ca-db6c-4878-b18d-2d7fe7999cb2.png)

This error message only exist in lite api

it appears that `require` import from firestore lite, and `import` import firestore

**Comment by tylim88** [comment] 2023-02-07 19:00
@ArStah @filmerjarred 

try v2.2.6, [release note](https://github.com/tylim88/FirelordJS/releases/tag/2.2.6)

**Comment by ArStah** [comment] 2023-02-08 07:32
My issue is resolved. Thanks!

**Closed** 2023-02-08 10:07 UTC
Labels: bug, good first issue
